# Generated by Django 2.2.7 on 2020-05-19 17:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_appointment', models.DateField(default=datetime.datetime.now)),
                ('duration_minutes', models.IntegerField()),
                ('special_instructions', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(max_length=200)),
                ('species', models.CharField(max_length=200)),
                ('breed', models.CharField(max_length=200)),
                ('weight_in_pounds', models.DecimalField(decimal_places=2, max_digits=5)),
                ('slug', models.CharField(blank=True, editable=False, max_length=200)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
